export const SOURCE_DOCUMENT_UPLOAD_LIMIT_BYTES = 50 * 1024 * 1024;
export const LEGACY_PDF_UPLOAD_LIMIT_BYTES = 4 * 1024 * 1024;
export const SOURCE_DOCUMENT_PAGE_LIMIT = 200;
export const SOURCE_DOCUMENT_ARTIFACT_CHARACTER_LIMIT = 200_000;
export const SOURCE_DOCUMENT_CONTEXT_CHARACTER_LIMIT = 50_000;
export const SOURCE_DOCUMENT_EXTRACTION_TIMEOUT_MS = 240_000;
export const SOURCE_DOCUMENT_UPLOAD_TTL_MS = 60 * 60 * 1000;
export const SOURCE_DOCUMENT_UPLOAD_PREFIX = 'source-documents/uploads/';

export const LEGACY_PDF_IMAGE_LIMIT = 20;
export const LEGACY_PDF_IMAGE_BYTES_LIMIT = 1024 * 1024;
export const LEGACY_PDF_TOTAL_IMAGE_BYTES_LIMIT = 4 * 1024 * 1024;
